# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-19 13:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CdnLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=32, verbose_name='游戏名')),
                ('version', models.CharField(max_length=32, verbose_name='资源版本')),
                ('is_full', models.BooleanField(default=True, verbose_name='是否增量')),
                ('user', models.CharField(max_length=32, verbose_name='操作人')),
                ('is_flush', models.BooleanField(default=False, verbose_name='是否需要刷新')),
                ('cdn_type', models.SmallIntegerField(choices=[(0, '国内'), (1, '海外')], default=0, verbose_name='CDN类型')),
                ('ctime', models.DateTimeField(default=datetime.datetime.now, verbose_name='执行时间')),
            ],
            options={
                'verbose_name': 'CDN执行日志',
                'verbose_name_plural': 'CDN执行日志',
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32, verbose_name='操作人')),
                ('gname', models.CharField(max_length=32, verbose_name='游戏名')),
                ('version_online', models.CharField(max_length=64, verbose_name='线上版本号')),
                ('version_updated', models.CharField(max_length=64, verbose_name='更新版本号')),
                ('game_package', models.CharField(default='', max_length=64, verbose_name='游戏包名')),
                ('game_type', models.SmallIntegerField(choices=[(0, '线上'), (1, '测试服')], default=1, verbose_name='是否线上服')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_new', models.BooleanField(choices=[(0, '当前版本'), (1, '跨版本')], default=0, verbose_name='是否跨版本')),
                ('ctime', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '游戏运维工作内容',
                'verbose_name_plural': '游戏运维工作内容',
            },
        ),
    ]
