# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-19 13:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userhostper',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='idc',
            name='servers',
            field=models.ManyToManyField(to='asset.Hosts'),
        ),
        migrations.AddField(
            model_name='hosts',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.HostUsers', verbose_name='系统用户'),
        ),
        migrations.AddField(
            model_name='hostgroup',
            name='host',
            field=models.ManyToManyField(to='asset.Hosts'),
        ),
    ]
