# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-19 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20190419_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostusers',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='密码'),
        ),
    ]
