# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-21 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_auto_20190419_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='disk',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='硬盘/G'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='game_id',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='GameID'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='memory',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='内存/G'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='server_id',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ServerID'),
        ),
    ]
