# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-19 13:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='结束时间')),
                ('channel', models.CharField(editable=False, max_length=100, unique=True, verbose_name='channel')),
                ('log', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='日志名')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('is_finished', models.BooleanField(default=False, verbose_name='是否完成')),
                ('width', models.PositiveIntegerField(default=90, verbose_name='宽度')),
                ('height', models.PositiveIntegerField(default=40, verbose_name='高度')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.Hosts', verbose_name='服务器')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'db_table': 'auditlog',
                'ordering': ['-start_time'],
                'permissions': (('can_delete_log', '可以删除审计日志'), ('can_view_log', '可以查看审计日志'), ('can_play_log', '可以播放审计日志')),
            },
        ),
        migrations.CreateModel(
            name='CommandLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='执行时间')),
                ('command', models.CharField(max_length=255, verbose_name='执行的命令')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webterminal.AuditLog', verbose_name='审计日志')),
            ],
            options={
                'verbose_name': '命令',
                'verbose_name_plural': '命令',
                'db_table': 'command',
                'ordering': ['-datetime'],
                'permissions': (('can_view_command_log', '可以查看历史执行命令'),),
            },
        ),
    ]
